ci: Make composer.json version check fail if PR modified version key

diff --git a/.github/workflows/version-check.yaml b/.github/workflows/version-check.yaml
--- a/.github/workflows/version-check.yaml
+++ b/.github/workflows/version-check.yaml
@@ -1,4 +1,4 @@
-name: Check composer.json Version Bumped
+name: Check composer.json Version Not Changed
 on:
   pull_request:
     types:
@@ -7,31 +7,16 @@ on:
 jobs:
   check-version-bumped:
     runs-on: ubuntu-latest
-    steps: 
+    steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - name: Check for releasable commit messages 
-        id: check_commit_messages
-        run: |
-          commits=$(git log --pretty=format:"%s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
-          if [[ $commits =~ "fix" || $commits =~ "feat" ]]; then
-            echo "Commit messages contain 'fix' or 'feat'. Running file check..."
-            echo "is_release=true" >> $GITHUB_OUTPUT
-          else
-            echo "Skipping further checks as this PR would not generate a release."
-            echo "is_release=false" >> $GITHUB_OUTPUT
-            exit 0
-          fi
       - name: Check Version Key Update
-        if: steps.check_commit_messages.outputs.is_release == 'true'
         id: check_version_changes
         run: |
-          changed_lines=$(git diff -r --unified=0 ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- composer.json | grep -c "version")
-          if [ "$changed_lines" -eq "0" ]; then
-            echo "Error: version in composer.json must be updated in the pull request"
+          changed_lines=$(git diff -r --unified=0 ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- composer.json | grep -c "version") || true
+          if [ "$changed_lines" -ne "0" ]; then
+            echo "Error: version in composer.json should not be updated manually."
             exit 1
           fi
-
-
