ci: check that version in composer.json is bumped

diff --git a/.github/workflows/version-check.yaml b/.github/workflows/version-check.yaml
--- a/.github/workflows/version-check.yaml
+++ b/.github/workflows/version-check.yaml
@@ -16,10 +16,18 @@ jobs:
         run: |
           commits=$(git log --pretty=format:"%s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
           if [[ $commits =~ "fix" || $commits =~ "feat" ]]; then
-            echo "Commit messages contain 'fix' or 'feat'. Running key check..."
+            echo "Commit messages contain 'fix' or 'feat'. Running file check..."
           else
-            echo "Skipping key check as commit messages do not contain 'fix' or 'feat'."
+            echo "Skipping further checks as this PR would not generate a release."
             exit 0
+          fi
+      - name: Check Version Key Update
+        id: check_version_changes
+        run: |
+          changed_lines=$(git diff -r --unified=0 ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- composer.json | grep -c "version")
+          if [ "$changed_lines" -eq "0" ]; then
+            echo "Error: version in composer.json must be updated in the pull request"
+            exit 1
           fi
 
 
